
(()=>{
const root=document.getElementById('tea-directions'), preview=root.querySelector('#tea-preview');
const docs=[['รายละเอียดการให้ทุนวิจัย ปี 2569','ทุนวิจัย','การให้ทุนอุดหนุนการวิจัย 69.pdf'],['ใบสมัครทุนวิจัย ปี 2569','ทุนวิจัย','ใบสมัครทุนวิจัย 69.pdf'],['เอกสารสนับสนุนบทความ • ตรวจชื่อก่อนย้าย','วารสาร','แบบขอรับเงินสนับสนุนบทความ.pdf'],['ประกาศหลักเกณฑ์สนับสนุนบทความ','วารสาร','ประกาศหลักเกณฑ์การให้เงินสนับสนุนบทความวิชาการ.pdf']];
const configs=[
['01','Institutional Elegance','ภูมิฐาน เป็นทางการ','กรมท่า × ทองอ่อน','เหมาะกับกรรมการที่ให้ความสำคัญกับความน่าเชื่อถือ เปิดด้วยพันธกิจสมาคม แล้วเข้าสู่ประกาศและเอกสาร','#183a50','#99722e','#f4f1e8','Columns + Group + Query Loop; เพิ่ม CSS สำหรับเส้นทองและตัวอักษร หัวเว็บเรียงลงหนึ่งคอลัมน์บนมือถือ','พื้นฐาน'],
['02','Clinical Clarity','สะอาด อ่านง่าย ใช้งานเร็ว','ขาว × เขียวอมฟ้า','เหมาะกับผู้ใช้หลากหลายวัย วางบริการหลักสามรายการทันทีใต้ข้อความเปิดหน้า','#164752','#11747c','#edf6f5','Group + Columns + Buttons + Query Loop; ใช้กริดการ์ดสามใบและระยะห่างสม่ำเสมอ','พื้นฐาน'],
['03','Academic Editorial','บุคลิกวารสารวิชาการ','หมึกดำ × กระดาษครีม','เหมาะกับการยกระดับภาพลักษณ์วิชาการ วารสารเป็นเรื่องเด่น ข่าวและทุนวิจัยเป็นคอลัมน์รอง','#302d29','#755331','#f0eadf','Columns + Heading + Query Loop; กำหนดฟอนต์หัวข้อแบบมีเชิงและเส้นคั่น ลิงก์ออกไปยังระบบวารสารเดิม','พื้นฐาน'],
['04','Resource First','ค้นเอกสารเป็นสิ่งแรก','น้ำเงิน × เทาอ่อน','เหมาะเมื่อผู้ใช้ส่วนใหญ่เข้ามาดาวน์โหลดแบบฟอร์ม ให้ช่องค้นและหมวดเอกสารอยู่เหนือข่าว','#213e65','#285db0','#edf2fa','สร้างประเภทเนื้อหาเอกสารและหมวดหมู่; หน้ารวมพร้อมตัวกรองต้องใช้ปลั๊กอินหรือโค้ดเพิ่ม การค้นในต้นแบบค้นเฉพาะชื่อ','เพิ่มเติม'],
['05','Scientific Forum','กิจกรรมวิชาการนำหน้า','พลัม × ชมพูอ่อน','เหมาะกับสมาคมที่สื่อสารงานประชุมสม่ำเสมอ แยกงานย้อนหลังกับกิจกรรมที่จะประกาศ ไม่แสดงงานเก่าว่ายังเปิดรับ','#472541','#8a3c6d','#f5edf3','Cover/Group + Columns + Query Loop หมวดกิจกรรม; ใช้ป้ายสถานะและปุ่มเชื่อมระบบใบประกาศเดิม','พื้นฐาน'],
['06','Member Service Desk','เมนูบริการตรงไปตรงมา','น้ำเงินเข้ม × มิ้นต์','เหมาะกับสมาชิกที่กลับมาใช้งานประจำ นำทางด้านซ้ายและวางงานที่ต้องทำตรงกลาง','#193d4a','#246a66','#eaf5ef','Columns + Navigation + Group; CSS สำหรับเมนูข้าง มือถือย้ายเป็นเมนูบน ระบบบัญชีสมาชิกหากต้องการต้องเพิ่มแยก','เพิ่มเติม'],
['07','Research Pathway','แนะนำการสมัครทุนทีละขั้น','เขียวป่า × งาช้าง','เหมาะกับการส่งเสริมงานวิจัย อธิบายลำดับอ่านเกณฑ์ เตรียมเอกสาร และตรวจช่องทางส่ง ลดการดาวน์โหลดผิดไฟล์','#234638','#39704c','#f0f3e8','Group + Columns + Details + File; สามขั้นเป็นเนื้อหาคงที่ ไม่ต้องมีระบบรับสมัครออนไลน์เพื่อใช้รูปแบบนี้','พื้นฐาน'],
['08','Open & Accessible','ตัวใหญ่ ทางเลือกน้อย','ดำ × เหลืองอุ่น','เหมาะกับผู้ใช้ที่ต้องการอ่านง่าย ไม่มีแบนเนอร์หมุน ใช้ลิงก์ข้อความขนาดใหญ่และลำดับสายตาชัดเจน','#252a2e','#61521c','#faf3d5','Heading + List + Buttons + File; เพิ่ม CSS focus และทดสอบคีย์บอร์ด/ความเปรียบต่างก่อนส่งจริง','พื้นฐาน'],
['09','Contemporary Mosaic','ทันสมัยด้วยกริดหลายขนาด','คราม × ลาเวนเดอร์','เหมาะกับการนำเสนอสมาคมยุคใหม่ แยกวารสาร ทุน และเอกสารเป็นพื้นที่เด่นคนละขนาด ลดความยาวส่วนเปิดหน้า','#33345d','#5d51a1','#f0eef9','Group + Columns หรือ CSS Grid เพิ่มเติม; กำหนดตำแหน่งการ์ดให้แน่นอนและเรียงตามความสำคัญบนมือถือ','เพิ่มเติม'],
['10','Human Connection','อบอุ่น เข้าถึงสมาคมง่าย','น้ำตาลแดง × พีช','เหมาะกับภาพลักษณ์ชุมชนวิชาชีพ แบ่งเส้นทางสมาชิกกับนักวิจัย และให้ช่องทางติดต่อเห็นง่าย','#55362d','#9a4b31','#faf0e8','Group + Columns + Buttons + Query Loop; ใช้สองเส้นทางแบบลิงก์หน้า ไม่จำเป็นต้องทำแท็บหรือระบบสมาชิก','พื้นฐาน']
];
const state={design:'01',radius:8};
const btn=(text,target='tea-docs')=>`<a class="cta" href="#${target}">${text} →</a>`;
const head=(k,t,p)=>`<div class="eyebrow">${k}</div><h1>${t}</h1><p>${p}</p>`;
const journal=()=>`<div class="poster"><span class="eyebrow">THAI ENDODONTIC JOURNAL</span><b>TEJ<br>Knowledge<br>in practice.</b><a href="https://he03.tci-thaijo.org/index.php/thaiendod" target="_blank" rel="noreferrer">อ่านวารสาร / ส่งบทความ ↗</a></div>`;
const news=()=>`<section id="tea-news" class="space"><h2>ข่าวและประกาศ</h2><div class="line"><div><span class="tag">ทุนวิจัย • 2569</span><h3>การให้ทุนอุดหนุนการวิจัย</h3></div><a href="#tea-docs">เอกสารที่เกี่ยวข้อง →</a></div><div class="line"><div><span class="tag">วารสาร</span><h3>เปิดรับบทความเพื่อตีพิมพ์ใน TEJ</h3></div><a href="https://he03.tci-thaijo.org/index.php/thaiendod" target="_blank" rel="noreferrer">ไปยังวารสาร ↗</a></div></section>`;
const services=()=>`<div class="three"><div class="tile"><span class="eyebrow">01 / KNOWLEDGE</span><h3>อ่านวารสาร</h3><a href="https://he03.tci-thaijo.org/index.php/thaiendod" target="_blank" rel="noreferrer">Thai Endodontic Journal ↗</a></div><div class="tile"><span class="eyebrow">02 / RESEARCH</span><h3>ทุนวิจัยและแบบฟอร์ม</h3><a href="#tea-docs">เลือกเอกสาร →</a></div><div class="tile"><span class="eyebrow">03 / SERVICES</span><h3>ใบประกาศกิจกรรม</h3><a href="https://www.thaiendodontics.com/" target="_blank" rel="noreferrer">ไปยังระบบเดิม ↗</a></div></div>`;
const library=(search=false)=>`<section id="tea-docs" class="library space"><h2>เอกสารดาวน์โหลด</h2>${search?'<label for="tea-search">ค้นหาจากชื่อเอกสาร</label><input id="tea-search" placeholder="เช่น ทุนวิจัย หรือ บทความ"><div class="filters"><button class="filter" data-cat="ทั้งหมด" aria-pressed="true">ทั้งหมด</button><button class="filter" data-cat="ทุนวิจัย" aria-pressed="false">ทุนวิจัย</button><button class="filter" data-cat="วารสาร" aria-pressed="false">วารสาร</button></div>':''}<div id="tea-doc-list" aria-live="polite"></div></section>`;
function render(){
const c=configs.find(x=>x[0]===state.design);preview.style.setProperty('--ink',c[5]);preview.style.setProperty('--accent',c[6]);preview.style.setProperty('--soft',c[7]);preview.style.setProperty('--radius',state.radius+'px');preview.style.setProperty('--paper',['03','07'].includes(c[0])?'#fffcf5':'#ffffff');
root.querySelector('#tea-choice').value=state.design;
root.querySelector('#tea-summary').innerHTML=`<strong>${c[0]} / ${c[1]} — ${c[2]}</strong><p>${c[3]} · ${c[4]}</p>`;
let body='';
switch(c[0]){
case '01':body=`<div class="wrap"><div class="split"><div class="serif">${head('THAI ENDODONTIC ASSOCIATION','ร่วมพัฒนาวิชาการ<br>เอ็นโดดอนติกส์ไทย','พื้นที่กลางสำหรับความรู้ งานวิจัย และการเชื่อมโยงวิชาชีพ')}${btn('สำรวจข่าวสมาคม','tea-news')}</div>${journal()}</div>${news()}${library()}</div>`;break;
case '02':body=`<div class="wrap">${head('KNOWLEDGE • RESEARCH • COMMUNITY','ทุกความรู้<br>เข้าถึงได้ง่ายขึ้น','ข่าวสารและบริการวิชาการสำหรับทันตแพทย์และผู้สนใจ')} ${services()}${news()}${library()}</div>`;break;
case '03':body=`<div class="bar"><span>THE ACADEMIC EDITION</span><span>วารสาร / งานวิจัย / ข่าวสมาคม</span></div><div class="wrap"><div class="split"><div class="serif">${head('FEATURED / JOURNAL','พื้นที่ของความรู้<br>ที่เติบโตไปด้วยกัน','อ่านวารสารและร่วมเผยแพร่องค์ความรู้ทางเอ็นโดดอนติกส์')}<a href="https://he03.tci-thaijo.org/index.php/thaiendod" target="_blank" rel="noreferrer">เปิด Thai Endodontic Journal ↗</a></div>${journal()}</div><div class="two">${news()}${library()}</div></div>`;break;
case '04':body=`<div class="wrap center">${head('RESOURCE LIBRARY','เอกสารที่ต้องการ<br>ค้นเจอได้ในที่เดียว','เลือกหมวดหมู่ หรือค้นหาชื่อแบบฟอร์ม')}</div><div class="wrap" style="padding-top:0">${library(true)}${news()}</div>`;break;
case '05':body=`<div class="wrap"><div class="split"><div>${head('SCIENTIFIC MEETING / ARCHIVE','เรียนรู้ร่วมกัน<br>ต่อยอดสู่การปฏิบัติ','กิจกรรมย้อนหลัง • 10 กรกฎาคม 2026')}<h3>Endodontic Uncovered</h3><p>Resolving Clinical Dilemmas Across Specialties</p><a class="cta" href="https://www.thaiendodontics.com/" target="_blank" rel="noreferrer">ไปยังระบบใบประกาศ ↗</a></div><div class="poster"><span>PAST EVENT</span><b>10<br>JUL<br>2026</b><span>กิจกรรมวิชาการสมาคม</span></div></div>${news()}${library()}</div>`;break;
case '06':body=`<div class="rail"><aside><strong>บริการสมาคม</strong><a href="#tea-docs">เอกสารดาวน์โหลด</a><a href="#tea-news">ประกาศล่าสุด</a><a href="https://he03.tci-thaijo.org/index.php/thaiendod" target="_blank" rel="noreferrer">วารสาร ↗</a><a href="#tea-contact">ติดต่อเจ้าหน้าที่</a></aside><div class="wrap">${head('SERVICE DESK','วันนี้ต้องการ<br>ทำอะไรกับสมาคม?','ทางลัดสำหรับบริการที่ใช้เป็นประจำ')}${services()}${library()}${news()}</div></div>`;break;
case '07':body=`<div class="wrap"><div class="center serif">${head('RESEARCH SUPPORT','เริ่มต้นงานวิจัย<br>ด้วยข้อมูลที่ครบถ้วน','ทุนอุดหนุนการวิจัย ประจำปี 2569')}</div><div class="three steps"><div class="tile"><h3>อ่านหลักเกณฑ์</h3><p>ตรวจคุณสมบัติและเงื่อนไขจากประกาศ</p><a href="#tea-docs">เปิดเอกสาร →</a></div><div class="tile"><h3>เตรียมใบสมัคร</h3><p>ใช้แบบฟอร์มตรงกับปีที่ประกาศ</p><a href="#tea-docs">เลือกแบบฟอร์ม →</a></div><div class="tile"><h3>ตรวจวิธีส่ง</h3><p>ยืนยันช่องทางและกำหนดการในประกาศ</p><a href="#tea-contact">สอบถามสมาคม →</a></div></div>${library()}${news()}</div>`;break;
case '08':body=`<div class="wrap">${head('สมาคมเอ็นโดดอนติกส์ไทย','ข้อมูลชัดเจน<br>บริการเข้าถึงง่าย','เลือกสิ่งที่คุณต้องการจากรายการด้านล่าง')}<div class="biglinks"><a href="#tea-docs">ดาวน์โหลดเอกสาร <span>↘</span></a><a href="https://he03.tci-thaijo.org/index.php/thaiendod" target="_blank" rel="noreferrer">อ่านวารสารและส่งบทความ <span>↗</span></a><a href="#tea-news">ข่าวและประกาศสมาคม <span>↘</span></a><a href="#tea-contact">ติดต่อสมาคม <span>↘</span></a></div>${library()}${news()}</div>`;break;
case '09':body=`<div class="wrap"><div class="two"><div class="tile">${head('TEA / CONNECT','ความรู้ที่เชื่อมโยง<br>ทั้งวิชาชีพ','ศูนย์กลางวิชาการเอ็นโดดอนติกส์ไทย')}${btn('อ่านประกาศ','tea-news')}</div>${journal()}</div><div class="two space"><div class="tile"><span class="eyebrow">RESEARCH / 2569</span><h2>ต่อยอดงานวิจัย</h2><a href="#tea-docs">ประกาศทุนและใบสมัคร →</a></div><div class="tile"><span class="eyebrow">QUICK ACCESS</span><h2>เอกสารพร้อมใช้</h2><a href="#tea-docs">เปิดคลังดาวน์โหลด →</a></div></div>${news()}${library()}</div>`;break;
case '10':body=`<div class="wrap"><div class="center serif">${head('A COMMUNITY OF KNOWLEDGE','เชื่อมความรู้<br>เชื่อมผู้คนในวิชาชีพ','สมาคมเอ็นโดดอนติกส์ไทย')}</div><div class="two"><div class="tile"><span class="eyebrow">FOR PRACTITIONERS</span><h2>สมาชิกและทันตแพทย์</h2><p>ติดตามข่าว กิจกรรม และบริการวิชาการ</p>${btn('ดูข่าวและบริการ','tea-news')}</div><div class="tile"><span class="eyebrow">FOR RESEARCHERS</span><h2>นักวิจัยและผู้เขียน</h2><p>เข้าถึงทุนวิจัยและเอกสารเกี่ยวกับบทความ</p>${btn('ค้นเอกสารวิชาการ')}</div></div>${news()}${library()}<div class="tile space"><h2>มีเรื่องให้สมาคมช่วย?</h2><a href="mailto:thaiendodontics@gmail.com">thaiendodontics@gmail.com ↗</a></div></div>`;break;
}
preview.innerHTML=`<header><div class="brand">สมาคมเอ็นโดดอนติกส์ไทย<small>THAI ENDODONTIC ASSOCIATION</small></div><nav aria-label="เมนูต้นแบบ"><a href="#tea-news">ข่าวสมาคม</a><a href="#tea-docs">เอกสาร</a><a href="#tea-contact">ติดต่อ</a></nav></header>${body}<footer id="tea-contact"><div><strong>สมาคมเอ็นโดดอนติกส์ไทย</strong><br>คณะทันตแพทยศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย</div><div><a href="tel:022188795">02-218-8795</a><br><a href="mailto:thaiendodontics@gmail.com">thaiendodontics@gmail.com</a></div></footer>`;
let cat='ทั้งหมด'; const fill=()=>{const q=(preview.querySelector('#tea-search')?.value||'').toLowerCase(); const matches=docs.filter(d=>(cat==='ทั้งหมด'||d[1]===cat)&&d[0].toLowerCase().includes(q));preview.querySelector('#tea-doc-list').innerHTML=matches.map(d=>`<div class="line"><div><span class="eyebrow">${d[1]} / PDF</span><h3>${d[0]}</h3></div><a href="https://www.thailandorganizer.com/thaiendodontics/${encodeURIComponent(d[2])}" target="_blank" rel="noreferrer">เปิด PDF ↗</a></div>`).join('')||'<p>ไม่พบเอกสาร ลองเปลี่ยนคำค้นหรือหมวดหมู่</p>';};fill();preview.querySelector('#tea-search')?.addEventListener('input',fill);preview.querySelectorAll('[data-cat]').forEach(b=>b.addEventListener('click',()=>{cat=b.dataset.cat;preview.querySelectorAll('[data-cat]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));fill();}));
root.querySelector('#tea-build').innerHTML=`<details open><summary>ทำจริงใน WordPress · งานระดับ${c[9]}</summary><p>${c[8]}</p></details><details><summary>โครงสร้างร่วมและขอบเขตต้นแบบ</summary><p>หน้าแรก / เกี่ยวกับสมาคม / ข่าวและกิจกรรม / วารสาร / ทุนวิจัย / คลังเอกสาร / ติดต่อ ใช้เนื้อหาที่มีผู้รับผิดชอบแก้ไขได้ แยกชื่อเอกสาร หมวด ปี วันที่ปรับปรุง และไฟล์ PDF</p><p>ตัวอย่างเป็นแนวทางหน้าตาและการจัดข้อมูล ไม่ใช่ธีม WordPress ที่ติดตั้งแล้ว ลิงก์ PDF เปิดแหล่งเดิม การค้นหาในแบบ 04 ทำงานเฉพาะรายการตัวอย่าง บริการวารสารและใบประกาศเชื่อมระบบเดิม โลโก้ใช้ชื่อสมาคมแทนตราที่ยังไม่ได้รับไฟล์ต้นฉบับ</p></details>`;
}
const picker=root.querySelector('#tea-choice');picker.innerHTML=configs.map(c=>`<option value="${c[0]}">${c[0]} · ${c[1]}</option>`).join('');picker.addEventListener('change',()=>{state.design=picker.value;render();});root.querySelector('#tea-device').addEventListener('change',e=>preview.classList.toggle('mobile',e.target.value==='mobile'));render();
if(globalThis.Tweak){const t=new Tweak({container:root,onChange:render});t.addSelect(state,'design',{label:'แนวทาง',options:configs.map(c=>({label:c[0]+' '+c[1],value:c[0]}))});t.addSlider(state,'radius',{label:'ความมนของกรอบ',min:0,max:24,unit:'px'});}
})();

